spring:
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
  datasource:
    url: "jdbc:h2:file:./data.db"
  h2:
    console:
      enabled: true
      path: "/h2"
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 'insert client id here'
            client-secret: 'insert client secret here'
            redirectUriTemplate: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile

app:
  auth:
    tokenSecret: 'insert jwt secret here'
    tokenExpirationMsec: 864000000
  oauth2:
    authorizedRedirectUris:
      - "http://localhost:3000/oauth2/redirect"

#logging.level.org.hibernate.SQL=debug
  jackson:
    date-format: com.fasterxml.jackson.databind.util.StdDateFormat
server:
  port: 9090
#Set username / password
wgms:
  user: 'insert wgms user here'
  pass: 'insert wgms password here'
#AIS database
ais:
  db: AISDB.csv
  username: 'inser ais username here'
# Google My Maps KMZ URL
kmz:
  url: https://www.google.com/maps/d/u/0/kml?mid=1C_guMPPn8sye2qoPgz9ciuN8Bsw
skip:
  db:
    initialization: true
falkor:
  underway:
    active: false
#Rockblock
rockblock:
  username: 'insert rockblock username here'
  password: 'insert rockblock password here'
#IMC id
ripples:
  imcid: 99
#GoogleApp

google:
  users:
    spreadsheet:
      id: 1m2EP30f-QeCQHMb-F7WLAj_xW_cw0NauA281LBUcUOA